### ISSUE TITLE
`fade` mixin, when set to show doesn't work.

### ISSUE THREAD

**Issue by aurooba** [bacoords/block-theme#207]
On `show` the code should be 

```scss
animation: fadeInAnimation ease-in 1s;
	animation-iteration-count: 1;
	@keyframes fadeInAnimation {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
```

Also, `show` should be the default, not hide.
