### ISSUE TITLE
Convert typography styles into mixins/full utility classes

### ISSUE THREAD

**Issue by bacoords** [bacoords/block-theme#227]
in theme.json you add default styles for headings, and then we also use those heading sizes as font sizes. Then in scss I typically add the other heading properties (like font, weight, spacing) to the utilty classes like this: 

```css
.has-h-2-font-size {
	letter-spacing: 4.8px;
	font-weight: 700;
	text-transform: uppercase;
	font-family: var(--wp--preset--font-family--addington-cf);
}
```

But I could probably parse that from theme.json and just generate it
